// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbyXigTQlwDs900HkK6cvgNzFF7FwUxNg',
    appId: '1:495962271669:web:3ac9934c161d599e7df3fc',
    messagingSenderId: '495962271669',
    projectId: 'fir-flutter-codelab-90067',
    authDomain: 'fir-flutter-codelab-90067.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-90067.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0_RgR5Z2yQFc0fYcXSGC8Vc8v2nRc4KA',
    appId: '1:495962271669:android:54b595c97a80065e7df3fc',
    messagingSenderId: '495962271669',
    projectId: 'fir-flutter-codelab-90067',
    storageBucket: 'fir-flutter-codelab-90067.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1JxnP8-nkvQLMM_dkN5v6re9Kmvv0VMo',
    appId: '1:495962271669:ios:a0c1b968ce4146117df3fc',
    messagingSenderId: '495962271669',
    projectId: 'fir-flutter-codelab-90067',
    storageBucket: 'fir-flutter-codelab-90067.appspot.com',
    iosClientId: '495962271669-54psbk13h7p0mjbo01sm70olphh616ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1JxnP8-nkvQLMM_dkN5v6re9Kmvv0VMo',
    appId: '1:495962271669:ios:a0c1b968ce4146117df3fc',
    messagingSenderId: '495962271669',
    projectId: 'fir-flutter-codelab-90067',
    storageBucket: 'fir-flutter-codelab-90067.appspot.com',
    iosClientId: '495962271669-54psbk13h7p0mjbo01sm70olphh616ei.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
